apiVersion: v1
kind: Service
metadata:
  name: kafka-keyvalue-nodejs--sidecar-demo
spec:
  ports:
    - name: demo
      port: 8080
      targetPort: 8080
    - name: kkv
      port: 8091
      targetPort: 8091
  selector:
    app: kafka-keyvalue-nodejs--sidecar-demo
---
apiVersion: v1
kind: Service
metadata:
  name: pixy
spec:
  ports:
    - port: 80
  selector:
    app: pixy