apiVersion: v1
kind: Service
metadata:
  name: kafka-keyvalue-nodejs--sidecar-demo
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: kafka-keyvalue-nodejs--sidecar-demo
---
apiVersion: v1
kind: Service
metadata:
  name: pixy
spec:
  ports:
    - port: 80
  selector:
    app: pixy