apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-keyvalue-nodejs--sidecar-demo
spec:
  selector:
    matchLabels:
      app: kafka-keyvalue-nodejs--sidecar-demo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kafka-keyvalue-nodejs--sidecar-demo
    spec:
      terminationGracePeriodSeconds: 1
      initContainers:
      - name: topic-configure
        image: solsson/kafka-cli@sha256:9fa3306e9f5d18283d10e01f7c115d8321eedc682f262aff784bd0126e1f2221
        resources:
          requests:
            cpu: 25m
            memory: 20Mi
          limits:
            cpu: 25m
            memory: 20Mi
        env:
        - name: ZOOKEEPER_CONNECT
          value: pzoo.kafka:2181
        command:
        - /bin/bash
        - -cex
        - >
          ./bin/kafka-topics.sh \
            --zookeeper $ZOOKEEPER_CONNECT \
            --topic sidecar-demo \
            --create \
            --if-not-exists \
            --partitions 50 \
            --replication-factor 1 \
            --config compression.type=uncompressed;
      containers:
      - name: demo
        image: builds-registry.ystack.svc.cluster.local/yolean/kafka-keyvalue-nodejs-demo
        ports:
        - containerPort: 8080
        env:
        - name: PIXY_HOST
          value: http://pixy.kafka
        - name: CACHE_HOST
          value: http://127.0.0.1:8091
        - name: TOPIC_NAME
          value: sidecar-demo
      - name: kv-cache
        image: solsson/kafka-keyvalue@sha256:84f71897ec55e13014049c49dfd81e2f99635515b7c88326b6b09cc4d132c3d0
        args:
        - -Dquarkus.http.port=8091
        ports:
        - containerPort: 8091
          name: api
        env:
        - name: kafka_bootstrap
          value: bootstrap.kafka:9092
        - name: kafka_group_id
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: topic
          value: sidecar-demo
        - name: kafka_max_poll_records
          value: "1000"
        - name: kafka_offset_reset
          value: latest
        - name: target
          value: http://127.0.0.1:8080/kafka-keyvalue/v1/updates
        readinessProbe:
          httpGet:
            path: /health/ready
            port: api
        livenessProbe:
          httpGet:
            path: /health/live
            port: api
          initialDelaySeconds: 30
          periodSeconds: 10
        resources:
          limits:
            memory: 100Mi
            cpu: 30m
          requests:
            memory: 100Mi
            cpu: 30m